# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'firas-bka-car'
primary_region = 'cdg'

[build]

  [build.args]

[env]
  APP_ENV = 'production'
  APP_DEBUG = 'false'
  APP_URL = 'https://firas-bka-car.fly.dev'
  DB_CONNECTION = 'pgsql'
  SESSION_DRIVER = 'database'
  CACHE_STORE = 'database'
  QUEUE_CONNECTION = 'database'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
